### ISSUE TITLE
TypeError: Cannot set property 'sign' of undefined

### ISSUE THREAD

**Issue by px05leexw** [dcloudio/uni-migration#23]
TypeError: Cannot set property 'sign' of undefined
    at module.exports (/usr/local/lib/node_modules/uni-migration/lib/index.js:1:669)
    at Object.<anonymous> (/usr/local/lib/node_modules/uni-migration/bin/uni-migration.js:44:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by px05leexw** [comment]
使用HBuilderX最新版，小程序拖进去没提示转化成快应用，创建快应用，选择从小程序转化，没转化。安装uni-migration，一下就报错。这个3个月没更新的工具真的能让小程序转快应用吗？

**Comment by Mopecat** [comment]
这个可能是不更新了，我跟你差不多 只转换了根目录的几个文件
