### ISSUE TITLE
小程序转快应用，编译时报错，不知道什么错误，有大神遇到过吗？

### ISSUE THREAD

**Issue by yilidan** [dcloudio/uni-migration#25]
[HBuilder] 16:01:42.316 D:\HBuilderX\HBuilderX\plugins\quickapp\src\app
[HBuilder] 16:01:42.318 D:\HBuilderX\HBuilderX\plugins\quickapp\node_modules\quickapp-tools\webpack.config.js:296
[HBuilder] 16:01:42.332       throw new Error(`Unknown node environment: ${NODE_ENV}`)
[HBuilder] 16:01:42.334       ^
[HBuilder] 16:01:42.346 Error: Unknown node environment: true-ol
[HBuilder] 16:01:42.348     at parse (D:\HBuilderX\HBuilderX\plugins\quickapp\node_modules\quickapp-tools\webpack.config.js:296:13)
[HBuilder] 16:01:42.360     at Object.<anonymous> (D:\HBuilderX\HBuilderX\plugins\quickapp\node_modules\quickapp-tools\webpack.config.js:124:18)
[HBuilder] 16:01:42.362     at Module._compile (module.js:652:30)
[HBuilder] 16:01:42.373     at Object.Module._extensions..js (module.js:663:10)
[HBuilder] 16:01:42.375     at Module.load (module.js:565:32)
[HBuilder] 16:01:42.387     at tryModuleLoad (module.js:505:12)
[HBuilder] 16:01:42.388     at Function.Module._load (module.js:497:3)
[HBuilder] 16:01:42.400     at Module.require (module.js:596:17)
[HBuilder] 16:01:42.402     at require (internal/module.js:11:18)
[HBuilder] 16:01:42.413     at requireConfig (D:\HBuilderX\HBuilderX\plugins\node_modules\webpack\bin\convert-argv.js:96:18)

**Comment by yilidan** [comment]
![image](https://user-images.githubusercontent.com/20895477/59747762-2ab44c00-92ac-11e9-8b22-04c9cadc7778.png)
